# Generated by Django 5.2.6 on 2025-09-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
