# Generated by Django 5.2.5 on 2025-09-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0004_employee2_delete_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee2",
        ),
    ]
